### ISSUE TITLE
align dialogs for swithching between sections

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/scoremodel#12]
The dialogs at top and bottom of the page to switch between sections are not in line with the frame of the main body of the page. 
They are now a bit more to the middle. Should be in line with the frame around the main section of the page.

**Comment by pieterdp** [comment]
Please provide a screenshot or a more detailed description of the problem. The dialogs are as a group in columns 3 till 10, making them nicely centered.

**Comment by bert-packed** [comment]
![dialogs](https://cloud.githubusercontent.com/assets/5360065/24646052/c838aba0-191a-11e7-80bb-7b826cd6d11b.png)
The buttons ' rapport bewerken' and '2. bewaarstrategie' are not in line with the frame that contains the questions. They should be moved a bit more to the outer sides of the page.
