### ISSUE TITLE
double title in dialogs under questions. 

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/scoremodel#13]
Now there is a label 'Context' in the tab of the dialog. And the label 'Context' appears again in the text field. 
Propose to remove the second one.

**Comment by pieterdp** [comment]
Conflicts with #11

**Comment by pieterdp** [comment]
The way it works now, clicking on a tab causes the linked content to expand, even if some other content (from another tab) is already expanded. Both blocks end up under each other, and without a title in the block itself, it is impossible for the user to know which block corresponds with which label.

**Comment by bert-packed** [comment]
fine.
