### ISSUE TITLE
new text for end report

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/scoremodel#16]
proposal for text and layout of the end report page.

- only two titles
- I would include the variables for report name, organisation name, user and date in natural language text. Variables in proposal below in square brackets.

titel: Score digitale duurzaamheid [organisatie]

Hieronder volgen de sterke en zwakke punten in de digitale huishouding van het [organisatie]. Dit rapport werd gemaakt door [gebruikersnaam] op [aanmaakdatum en -tijd] met behulp van het [rapportsjabloon].

[grafiek]

Het netwerkdiagram hierboven toont de scores van [instellingsnaam] voor de zeven aspecten die de duurzaamheid bepalen van de digitale bestanden die ze bewaart. Hoe beter [organisatie] scoort voor een aspect, hoe verder de marker naar de buitenkant van het diagram schuift. Bevindt de marker zich in de rode zone van het diagram, dan zijn de digitale bestanden in gevaar. Bevindt hij zich in de gele zone, dan is het ergste gevaar geweken. Bevindt hij zich in de groene zone, dan heeft [organisatie] alles gedaan wat redelijkerwijs mogelijk is om de bestanden duurzaam te bewaren. 

Waar precies de grens ligt tussen gevaarlijk en veilig, hangt af van de norm die je gebruikt. De oranje zevenhoek geeft de score weer volgens de DSA-norm. De blauwe zevenhoek geeft de score weer als je alle vragen van het scoremodel in overweging neemt.

titel: Actieplan

Hieronder volgen de vijf prioritaire acties die [organisatie] kan nemen om de grootste risio's voor de duurzaamheid van je digitale bestanden te verkleinen.

**Comment by bert-packed** [comment]
addition. to be added under initial paragraph, jus before the diagram
Een volledig overzicht van alle antwoorden vind je op deze [[volledig rapport|pagina]].

**Comment by pieterdp** [comment]
This has partially been done (lacking translations), but please note the following:

The "summary" and "report" pages are dynamically generated with data from the DB that is linked to a specific report template. This allows us to support multiple report templates, but implies that any "strings" (text, graphics, titles) on the pages must be generic enough to be applicable to all possible report templates. I have thus scrapped all report-specific contents and replaced them with something more generic.
