### ISSUE TITLE
layout diagram

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/scoremodel#17]
proposal for the diagram:

- background of the diagram should be coloured: red up to 50% scores, yellow up to 90% scores, green for the last 10%.
- 50% transparency for the background colors
- heptagons should be without color filling. 
- When hovering over the heptagon, transparency of the diagram background should be 0%

So when hovering over one of the heptagons, the user should notice where he is in the red, yellow or green zone.

Labels for the seven dimensions should be larger and outside the diagram.

**Comment by pieterdp** [comment]
This is not possible with the current graphics library. Changing the library is currently not feasible.

**Comment by bert-packed** [comment]
Then come at least with a proposal which is feasible. 

At least the position of the labels in the diagram has to be improved.

**Comment by pieterdp** [comment]
None of the requested modifications is possible using the [current](https://github.com/alangrafu/radar-chart-d3) graphics library. FLOSS-D3-based RadarCharts are not plentiful, so the choice is limited to the options this library provides.

Choosing a different graphics library (if one exists) would require refactoring the report page UI and probably parts of the API as well. This is not feasible. Creating one from scratch, using basic D3js, would require even more work, and quality isn't guaranteed.

Repositioning the labels is not possible. Enlarging them might be by using some CSS.

Please also note that the graph is generated dynamically based on the sections in the report template. A report can have more or less than 7 sections, as well as multiple benchmarks.
